# Generated by Django 4.0.6 on 2022-07-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
