# Generated by Django 4.0.3 on 2022-03-29 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Post must be at least 5 characters long.'), django.core.validators.MaxLengthValidator(280, 'Post must be at most 280 characters long.')]),
        ),
    ]
