# Generated by Django 4.0.3 on 2022-04-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publication_date']},
        ),
    ]
