# Generated by Django 4.0.6 on 2022-07-07 19:55

from django.db import migrations
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', network.models.CustomUserManager()),
            ],
        ),
    ]
