# Generated by Django 4.0.5 on 2022-06-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
