# Generated by Django 4.0.5 on 2022-06-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
