# Generated by Django 4.0.5 on 2022-06-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publication_date']},
        ),
    ]
