# Generated by Django 4.0.5 on 2022-06-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publication_date']},
        ),
    ]
